# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  app-dev:
    build:
      context: .
      target: dev
    ports:
      - '3000:3000'
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: package.json
    profiles: ['dev']

  # Production service
  app-prod:
    build:
      context: .
      target: prod
    ports:
      - '3000:3000'
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles: ['prod']
